# Generated by Django 3.1.7 on 2021-03-31 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='v_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, unique=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('one_day_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_hours', models.IntegerField(default=0)),
                ('location_city', models.CharField(max_length=120)),
                ('location_street', models.CharField(max_length=120)),
                ('location_number', models.IntegerField()),
                ('description', models.TextField()),
                ('all_day', models.BooleanField(default=False)),
                ('is_license', models.BooleanField(default=False)),
                ('is_food', models.BooleanField(default=False)),
                ('is_physical', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
