# Generated by Django 3.1.7 on 2021-03-31 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_auto_20210331_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 3, 31)),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2021, 3, 31, 16, 53, 58, 442841)),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='one_day_date',
            field=models.DateField(default=datetime.date(2021, 3, 31)),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 3, 31)),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2021, 3, 31, 16, 53, 58, 442841)),
        ),
    ]
